"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { AppTopbar } from "@/components/app/Topbar";
import { Card, EmptyState, ErrorBox, PageContainer, formatNgn } from "@/components/app/ui";
import { useToast } from "@/components/ui/Toast";
type Payment={sequence:number;kind:string;percentage:number;amount:number;dueDate:string;status:string;reference?:string;proofUrl?:string}; type Purchase={id:string;status:string;totalPrice:number;totalPaid:number;outstandingBalance:number;buyer?:{firstName?:string;lastName?:string;email?:string};property?:{name?:string};unit?:{listingTitle?:string};payments:Payment[]};
export default function Page(){const qc=useQueryClient();const toast=useToast();const q=useQuery({queryKey:["sale-purchases","seller"],queryFn:async()=> (await api.get<{data:Purchase[]}>("/sale-purchases/seller")).data.data});const review=useMutation({mutationFn:({id,sequence,approved}:{id:string;sequence:number;approved:boolean})=>api.post(`/sale-purchases/${id}/payments/${sequence}/review`,{approved}),onSuccess:(_,v)=>{qc.invalidateQueries({queryKey:["sale-purchases","seller"]});toast.success(v.approved?"Payment confirmed":"Payment rejected")}});return <><AppTopbar title="Property sales" subtitle="Review buyer payment claims and track purchase-plan progress"/><PageContainer>{q.isError?<ErrorBox message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:q.data?.length?<div className="space-y-5">{q.data.map(p=><Card key={p.id} className="overflow-hidden"><div className="flex justify-between gap-4 border-b border-foundation-700/10 p-5"><div><p className="text-lg font-bold text-foundation-700">{p.unit?.listingTitle||p.property?.name||"Property purchase"}</p><p className="text-sm text-ink-muted">{p.buyer?.firstName} {p.buyer?.lastName} · {p.buyer?.email}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold capitalize text-emerald-800">{p.status.replace("_"," ")}</span></div><div className="grid gap-3 border-b border-foundation-700/10 p-5 sm:grid-cols-3"><Metric label="Sale price" value={formatNgn(p.totalPrice)}/><Metric label="Confirmed" value={formatNgn(p.totalPaid)}/><Metric label="Outstanding" value={formatNgn(p.outstandingBalance)}/></div>{p.payments.map(x=><div key={x.sequence} className="flex flex-wrap items-center justify-between gap-3 border-b border-foundation-700/10 p-5"><div><p className="font-semibold text-foundation-700">{x.kind} · {formatNgn(x.amount)}</p><p className="text-sm text-ink-muted">{x.percentage}% · {x.status.replace("_"," ")}{x.reference?` · Ref: ${x.reference}`:""}</p></div>{x.status==="proof_submitted"&&<div className="flex gap-2">{x.proofUrl&&<a href={x.proofUrl} target="_blank" rel="noreferrer" className="rounded-full border border-foundation-700/15 px-3 py-2 text-xs font-semibold text-foundation-700">View receipt</a>}<button onClick={()=>review.mutate({id:p.id,sequence:x.sequence,approved:true})} className="rounded-full bg-foundation-700 px-3 py-2 text-xs font-semibold text-paper">Confirm</button><button onClick={()=>review.mutate({id:p.id,sequence:x.sequence,approved:false})} className="rounded-full border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Reject</button></div>}</div>)}</Card>)}</div>:<EmptyState title="No property sales yet" body="Buyer payment plans will appear here for review."/>}</PageContainer></>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-[11px] font-semibold uppercase tracking-[0.13em] text-ink-muted">{label}</p><p className="mt-1 text-lg font-bold text-foundation-700">{value}</p></div>}
