"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, ExternalLink, Hotel, Settings2 } from "lucide-react";
import { AppTopbar } from "@/components/app/Topbar";
import { Card, ErrorBox, PageContainer, Skeleton, formatNgn } from "@/components/app/ui";
import { landlordApi, Unit } from "@/lib/landlord-api";
import { hotelBookingApi } from "@/lib/hotel-booking-api";
import { api } from "@/lib/api";

export default function HotelDeskPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const queryClient = useQueryClient();
  const hotel = useQuery({ queryKey: ["hotel-desk", id], queryFn: () => landlordApi.getProperty(id), enabled: !!id });
  const bookings = useQuery({ queryKey: ["hotel-bookings", "host"], queryFn: hotelBookingApi.forHost });
  const saveProfile = useMutation({ mutationFn: (hotelProfile: Record<string, string>) => landlordApi.updateProperty(id, { hotelProfile }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["hotel-desk", id] }) });
  if (hotel.isLoading) return <PageContainer><Skeleton className="h-10 w-64" /></PageContainer>;
  if (hotel.isError || !hotel.data) return <PageContainer><ErrorBox message={hotel.error instanceof Error ? hotel.error.message : "Hotel not found"} onRetry={() => hotel.refetch()} /></PageContainer>;
  const { property, units } = hotel.data;
  const propertyBookings = (bookings.data ?? []).filter((booking) => booking.property?._id === id);
  const pending = propertyBookings.filter((booking) => booking.status === "pending");
  return <>
    <AppTopbar title={property.name} subtitle="Hotel operator desk" actions={<Link href={`/hotels/${id}`} target="_blank" className="inline-flex items-center gap-1.5 rounded-full border border-foundation-700/15 px-4 py-2 text-[12.5px] font-semibold text-foundation-700"><ExternalLink className="h-4 w-4" /> View public page</Link>} />
    <PageContainer>
      <div className="grid gap-4 lg:grid-cols-3">
        <Card className="p-5"><Hotel className="h-5 w-5 text-foundation-700" /><p className="mt-5 text-2xl font-semibold text-foundation-700">{units.length}</p><p className="mt-1 text-[12.5px] text-ink-muted">Rooms configured</p></Card>
        <Card className="p-5"><CalendarDays className="h-5 w-5 text-foundation-700" /><p className="mt-5 text-2xl font-semibold text-foundation-700">{pending.length}</p><p className="mt-1 text-[12.5px] text-ink-muted">Bookings awaiting response</p></Card>
        <Card className="p-5"><Settings2 className="h-5 w-5 text-foundation-700" /><p className="mt-5 text-[15px] font-semibold text-foundation-700">Hotel profile</p><p className="mt-1 text-[12.5px] text-ink-muted">Check-in {property.hotelProfile?.checkInTime ?? "not set"} · Check-out {property.hotelProfile?.checkOutTime ?? "not set"}</p><Link href={`/app/properties/${id}`} className="mt-4 inline-block text-[12px] font-semibold text-foundation-700 underline decoration-cryola-400 underline-offset-4">Edit hotel and rooms</Link></Card>
      </div>
      <Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-foundation-700/10 px-5 py-4"><div><p className="text-[14.5px] font-semibold text-foundation-700">Booking queue</p><p className="mt-0.5 text-[12px] text-ink-muted">Recent requests for this hotel</p></div></div>{propertyBookings.length ? <div className="divide-y divide-foundation-700/10">{propertyBookings.slice(0, 8).map((booking) => <div key={booking._id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="text-[13.5px] font-semibold text-foundation-700">{booking.guest?.firstName ?? "Guest"} {booking.guest?.lastName ?? ""} · {booking.unit?.listingTitle ?? booking.unit?.unitNumber ?? "Room"}</p><p className="mt-1 text-[12px] text-ink-muted">{new Date(booking.checkIn).toLocaleDateString()} – {new Date(booking.checkOut).toLocaleDateString()}</p></div><div className="text-right"><p className="text-[13px] font-semibold text-foundation-700">{formatNgn(booking.totalAmount)}</p><p className="mt-1 text-[11px] capitalize text-ink-muted">{booking.status}</p></div></div>)}</div> : <p className="px-5 py-8 text-[13px] text-ink-muted">No booking requests for this hotel yet.</p>}</Card>
      <HotelProfileForm initial={property.hotelProfile ?? {}} saving={saveProfile.isPending} onSave={(profile) => saveProfile.mutate(profile)} />
      <RoomInventory propertyId={id} rooms={units} onChanged={() => queryClient.invalidateQueries({ queryKey: ["hotel-desk", id] })} />
      <BookingInbox bookings={propertyBookings} onChanged={() => bookings.refetch()} />
    </PageContainer>
  </>;
}

function HotelProfileForm({ initial, saving, onSave }: { initial: Record<string, string>; saving: boolean; onSave: (data: Record<string, string>) => void }) {
  return <Card className="mt-6 p-5"><p className="text-[14.5px] font-semibold text-foundation-700">Stay policy and contact</p><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ checkInTime: String(form.get("checkInTime") ?? ""), checkOutTime: String(form.get("checkOutTime") ?? ""), contactPhone: String(form.get("contactPhone") ?? ""), cancellationPolicy: String(form.get("cancellationPolicy") ?? "") }); }} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[12px] font-medium text-foundation-700">Check-in<input name="checkInTime" type="time" defaultValue={initial.checkInTime || "14:00"} className="mt-1 block w-full rounded-xl border border-foundation-700/15 bg-paper px-3 py-2 text-[13px]" /></label><label className="text-[12px] font-medium text-foundation-700">Check-out<input name="checkOutTime" type="time" defaultValue={initial.checkOutTime || "12:00"} className="mt-1 block w-full rounded-xl border border-foundation-700/15 bg-paper px-3 py-2 text-[13px]" /></label><label className="text-[12px] font-medium text-foundation-700 sm:col-span-2">Booking phone<input name="contactPhone" defaultValue={initial.contactPhone || ""} className="mt-1 block w-full rounded-xl border border-foundation-700/15 bg-paper px-3 py-2 text-[13px]" /></label><label className="text-[12px] font-medium text-foundation-700 sm:col-span-2">Cancellation policy<textarea name="cancellationPolicy" defaultValue={initial.cancellationPolicy || ""} rows={3} className="mt-1 block w-full rounded-xl border border-foundation-700/15 bg-paper px-3 py-2 text-[13px]" /></label><button disabled={saving} className="w-fit rounded-full bg-foundation-700 px-4 py-2 text-[12px] font-semibold text-paper disabled:opacity-50">{saving ? "Saving…" : "Save hotel page"}</button></form></Card>;
}

function RoomInventory({ propertyId, rooms, onChanged }: { propertyId: string; rooms: Array<Unit & { listingTitle?: string }>; onChanged: () => void }) {
  const add = useMutation({ mutationFn: async (data: FormData) => { const room = await landlordApi.addUnit(propertyId, { unitNumber: String(data.get("unitNumber")), bedrooms: Number(data.get("bedrooms")), bathrooms: Number(data.get("bathrooms")), rentAmount: Number(data.get("nightlyRate")), rentPeriod: "daily" }); await landlordApi.listUnit(room._id, { visibility: "public", listingPurpose: "shortlet", listingTitle: String(data.get("title")), listingDetails: { minimumStayNights: Number(data.get("minimumStay")) || 1, maxGuests: Number(data.get("maxGuests")) || 2 } }); }, onSuccess: onChanged });
  return <Card className="mt-6 p-5"><p className="text-[14.5px] font-semibold text-foundation-700">Room inventory</p><p className="mt-1 text-[12px] text-ink-muted">Add a room as a shortlet to publish it on the hotel page.</p><div className="mt-3 divide-y divide-foundation-700/10">{rooms.map((room) => <div key={String(room._id)} className="flex justify-between gap-3 py-3 text-[13px]"><span className="font-medium text-foundation-700">{String(room.listingTitle ?? room.unitNumber ?? "Room")}</span><span className="text-ink-muted">{formatNgn(Number(room.rentAmount ?? 0))}/night</span></div>)}</div><form onSubmit={(event) => { event.preventDefault(); add.mutate(new FormData(event.currentTarget)); event.currentTarget.reset(); }} className="mt-4 grid gap-2 sm:grid-cols-3"><input required name="title" placeholder="Room name" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input required name="unitNumber" placeholder="Room number" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input required name="nightlyRate" type="number" min="1" placeholder="Nightly rate" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input name="maxGuests" type="number" min="1" defaultValue="2" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input name="minimumStay" type="number" min="1" defaultValue="1" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input name="bedrooms" type="number" min="0" defaultValue="1" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><input name="bathrooms" type="number" min="0" defaultValue="1" className="rounded-xl border border-foundation-700/15 px-3 py-2 text-[13px]" /><button disabled={add.isPending} className="rounded-xl bg-foundation-700 px-3 py-2 text-[12px] font-semibold text-paper disabled:opacity-50">{add.isPending ? "Adding…" : "Add room"}</button></form></Card>;
}

function BookingInbox({ bookings, onChanged }: { bookings: Array<{ _id: string; status: string; unit?: { listingTitle?: string; unitNumber?: string }; guest?: { firstName?: string; lastName?: string } }>; onChanged: () => void }) {
  const action = useMutation({ mutationFn: ({ id, status }: { id: string; status: "confirmed" | "cancelled" }) => api.patch(`/hotel-bookings/${id}`, { status }), onSuccess: onChanged });
  return <Card className="mt-6 p-5"><p className="text-[14.5px] font-semibold text-foundation-700">Booking actions</p><div className="mt-3 divide-y divide-foundation-700/10">{bookings.filter((booking) => booking.status === "pending").map((booking) => <div key={booking._id} className="flex items-center justify-between gap-3 py-3"><p className="text-[13px] text-foundation-700">{booking.unit?.listingTitle ?? booking.unit?.unitNumber ?? "Room"} · {booking.guest?.firstName ?? "Guest"} {booking.guest?.lastName ?? ""}</p><div className="flex gap-2"><button onClick={() => action.mutate({ id: booking._id, status: "confirmed" })} className="rounded-full bg-foundation-700 px-3 py-1.5 text-[11px] font-semibold text-paper">Confirm</button><button onClick={() => action.mutate({ id: booking._id, status: "cancelled" })} className="rounded-full border border-foundation-700/15 px-3 py-1.5 text-[11px] font-semibold text-foundation-700">Decline</button></div></div>)}{!bookings.some((booking) => booking.status === "pending") && <p className="py-3 text-[13px] text-ink-muted">No booking actions waiting.</p>}</div></Card>;
}
