"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppTopbar } from "@/components/app/Topbar";
import { Card, PageContainer } from "@/components/app/ui";
import { landlordApi } from "@/lib/landlord-api";
import { api, unwrap } from "@/lib/api";

export default function HotelManagerPage() {
  const { id } = useParams<{ id: string }>();
  const qc = useQueryClient();
  const hotel = useQuery({ queryKey: ["property", id], queryFn: () => landlordApi.getProperty(id) });
  const bookings = useQuery({ queryKey: ["hotel-bookings", "host"], queryFn: async () => unwrap<any[]>((await api.get("/hotel-bookings/host")).data), refetchInterval: 30_000 });
  const save = useMutation({ mutationFn: (hotelProfile: { checkInTime?: string; checkOutTime?: string; contactPhone?: string; cancellationPolicy?: string }) => landlordApi.updateProperty(id, { hotelProfile }), onSuccess: () => qc.invalidateQueries({ queryKey: ["property", id] }) });
  if (hotel.isLoading) return <PageContainer>Loading hotel…</PageContainer>;
  const property = hotel.data?.property;
  if (!property || property.propertyType !== "hotel") return <PageContainer>Hotel not found.</PageContainer>;
  const refresh = () => qc.invalidateQueries({ queryKey: ["property", id] });

  return <><AppTopbar title={property.name} subtitle="Hotel storefront management" actions={<Link href={`/hotels/${id}`} className="rounded-full border border-foundation-700/15 px-4 py-2 text-xs font-semibold">View public page</Link>} /><PageContainer><div className="mx-auto grid max-w-3xl gap-5">
    <Card className="p-6"><h2 className="font-semibold">Public hotel page</h2><p className="mt-2 text-sm text-ink-muted">Your hotel page uses this property&apos;s photos, description, address, amenities, and active shortlet rooms.</p><Link href={`/hotels/${id}`} className="mt-4 inline-block text-sm font-semibold text-foundation-700 underline">Open hotel storefront</Link></Card>
    <HotelProfileForm initial={property.hotelProfile ?? {}} saving={save.isPending} onSave={(data) => save.mutate(data)} />
    <RoomInventory propertyId={id} rooms={hotel.data?.units ?? []} onChanged={refresh} />
    <BookingInbox bookings={bookings.data ?? []} onChanged={() => bookings.refetch()} />
  </div></PageContainer></>;
}

function HotelProfileForm({ initial, saving, onSave }: { initial: any; saving: boolean; onSave: (data: any) => void }) {
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); onSave({ checkInTime: data.get("checkInTime"), checkOutTime: data.get("checkOutTime"), contactPhone: data.get("contactPhone"), cancellationPolicy: data.get("cancellationPolicy") }); };
  return <Card className="p-6"><h2 className="font-semibold">Stay policy and contact</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Check-in<input name="checkInTime" type="time" defaultValue={initial.checkInTime || "14:00"} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Check-out<input name="checkOutTime" type="time" defaultValue={initial.checkOutTime || "12:00"} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm sm:col-span-2">Booking phone<input name="contactPhone" defaultValue={initial.contactPhone || ""} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm sm:col-span-2">Cancellation policy<textarea name="cancellationPolicy" defaultValue={initial.cancellationPolicy || ""} rows={4} className="mt-1 w-full rounded-lg border p-2" /></label><button disabled={saving} className="w-fit rounded-full bg-foundation-700 px-5 py-2.5 text-sm font-semibold text-paper disabled:opacity-50">{saving ? "Saving…" : "Save hotel page"}</button></form></Card>;
}

function RoomInventory({ propertyId, rooms, onChanged }: { propertyId: string; rooms: any[]; onChanged: () => void }) {
  const add = useMutation({ mutationFn: async (data: FormData) => { const room = await landlordApi.addUnit(propertyId, { unitNumber: String(data.get("unitNumber")), bedrooms: Number(data.get("bedrooms")), bathrooms: Number(data.get("bathrooms")), rentAmount: Number(data.get("nightlyRate")), rentPeriod: "daily" }); await landlordApi.listUnit(room._id, { visibility: "public", listingPurpose: "shortlet", listingTitle: String(data.get("title")), listingDetails: { minimumStayNights: Number(data.get("minimumStay")) || 1, maxGuests: Number(data.get("maxGuests")) || 2, serviceCharge: Number(data.get("serviceCharge")) || 0 } }); }, onSuccess: onChanged });
  const availability = useMutation({ mutationFn: async (room: any) => { const unitId = room._id; if (room.isListed) return landlordApi.unlistUnit(unitId); return landlordApi.listUnit(unitId, { visibility: "public", listingPurpose: "shortlet", listingTitle: room.listingTitle, listingDescription: room.listingDescription, listingDetails: room.listingDetails }); }, onSuccess: onChanged });
  return <Card className="p-6"><h2 className="font-semibold">Rooms</h2><p className="mt-1 text-sm text-ink-muted">Remove a room from the public page whenever it is unavailable. Re-publishing sends it for review again.</p><div className="mt-3 divide-y divide-foundation-700/10">{rooms.map((room) => <div key={room._id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><span>{room.listingTitle || `Room ${room.unitNumber}`} <span className="text-ink-muted">· up to {room.listingDetails?.maxGuests || 2} guests · {room.isListed ? "listed" : "not listed"}</span></span><div className="flex items-center gap-3"><span className="text-ink-muted">₦{Number(room.rentAmount).toLocaleString()}/night</span><button onClick={() => availability.mutate(room)} disabled={availability.isPending} className="rounded-full border border-foundation-700/20 px-3 py-1.5 text-xs font-semibold">{room.isListed ? "Pause" : "Publish"}</button></div></div>)}{!rooms.length && <p className="py-3 text-sm text-ink-muted">No rooms yet.</p>}</div><form onSubmit={(e) => { e.preventDefault(); add.mutate(new FormData(e.currentTarget)); e.currentTarget.reset(); }} className="mt-5 grid gap-3 sm:grid-cols-2"><input name="title" required placeholder="Room name, e.g. Deluxe king" className="rounded-lg border p-2" /><input name="unitNumber" required placeholder="Room number" className="rounded-lg border p-2" /><input name="nightlyRate" required type="number" min="1" placeholder="Nightly rate (₦)" className="rounded-lg border p-2" /><input name="minimumStay" type="number" min="1" defaultValue="1" placeholder="Minimum nights" className="rounded-lg border p-2" /><input name="maxGuests" required type="number" min="1" max="20" defaultValue="2" placeholder="Maximum guests" className="rounded-lg border p-2" /><input name="bedrooms" type="number" min="0" defaultValue="1" className="rounded-lg border p-2" /><input name="bathrooms" type="number" min="0" defaultValue="1" className="rounded-lg border p-2" /><input name="serviceCharge" type="number" min="0" defaultValue="0" placeholder="Service charge (₦)" className="rounded-lg border p-2" /><button disabled={add.isPending} className="rounded-full bg-foundation-700 px-4 py-2 text-sm font-semibold text-paper disabled:opacity-50">{add.isPending ? "Adding…" : "Add and publish room"}</button></form>{add.isError && <p className="mt-3 text-sm text-error">Could not add the room. Check the details and try again.</p>}{availability.isError && <p className="mt-3 text-sm text-error">Could not update room availability. Try again.</p>}</Card>;
}

function BookingInbox({ bookings, onChanged }: { bookings: any[]; onChanged: () => void }) {
  const act = useMutation({ mutationFn: ({ id, status }: { id: string; status: "confirmed" | "cancelled" }) => api.patch(`/hotel-bookings/${id}`, { status }), onSuccess: onChanged });
  return <Card className="p-6"><h2 className="font-semibold">Booking requests</h2><div className="mt-3 divide-y divide-foundation-700/10">{bookings.map((booking) => <div key={booking._id || booking.id} className="flex flex-wrap items-center justify-between gap-3 py-4 text-sm"><div><p className="font-medium">{booking.unit?.listingTitle || booking.unit?.unitNumber} · {booking.guest?.firstName} {booking.guest?.lastName}</p><p className="text-ink-muted">{new Date(booking.checkIn).toLocaleDateString()} – {new Date(booking.checkOut).toLocaleDateString()} · {booking.guests} guest(s)</p></div>{booking.status === "pending" ? <div className="flex gap-2"><button onClick={() => act.mutate({ id: booking._id || booking.id, status: "confirmed" })} className="rounded-full bg-foundation-700 px-3 py-1.5 text-xs font-semibold text-paper">Confirm</button><button onClick={() => act.mutate({ id: booking._id || booking.id, status: "cancelled" })} className="rounded-full border px-3 py-1.5 text-xs font-semibold">Decline</button></div> : <span className="capitalize text-ink-muted">{booking.status}</span>}</div>)}{!bookings.length && <p className="py-3 text-sm text-ink-muted">No booking requests yet.</p>}</div></Card>;
}
